# 架构映射
arch_mapping:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm32
  default: amd64

# 控制端 软件包位置
current_arch: "{{ arch_mapping[ansible_architecture] | default(arch_mapping.default) }}"
package_dir: "{{ [playbook_dir | dirname, 'packages'] | path_join }}"
calico_package_dir: "{{ package_dir }}/cni/{{ cluster_cni }}/{{ calico_version }}/{{ current_arch }}"
