---
- name: 分发历史命令配置文件
  template:
    src: 99-ikubeops-history.sh.j2
    dest: /etc/profile.d/99-ikubeops-history.sh
    mode: '0644'
    backup: yes

- name: 历史命令配置信息
  debug:
    msg: "Bash 历史命令已优化，重新登录后生效"
