---
- name: 确定目标系统的 vimrc 路径
  set_fact:
    vimrc_path: "{{ '/etc/vim/vimrc' if ansible_distribution in ['Ubuntu', 'Debian'] else '/etc/vimrc' }}"

- name: 优化vim配置
  blockinfile:
    path: "{{ vimrc_path }}"
    create: yes # 如果文件不存在则创建
    marker: '" {mark} ANSIBLE MANAGED BLOCK - VIM OPTIMIZATION'
    block: |
      " 基本设置
      set ts=4 
      set softtabstop=4 
      set tabstop=4 
      set shiftwidth=4 
      set expandtab 
      set autoindent 
      set cursorline 
      set ruler 
      set fenc=utf-8 
      set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936 
      set nocompatible 
      syntax enable 
      syntax on 

      " YAML 文件特殊处理
      autocmd FileType yaml setlocal indentkeys-=0# ts=2 sw=2 et
      autocmd FileType yml setlocal ai ts=2 sw=2 et

      " 新建文件自动添加文件头
      autocmd BufNewFile *.py,*.sh exec ":call SetTitle()"
      let $author_name = "Yan Shicheng"
      let $author_email = "yans121@sina.com"

      func SetTitle()
        if &filetype == 'sh'
          call setline(1,"\#!/bin/bash")
          call append(line("."), "\#File Name    : ".expand("%"))
          call append(line(".")+1, "\#Author       : ".$author_name)
          call append(line(".")+2, "\#Mail         : ".$author_email)
          call append(line(".")+3, "\#Create Time  : ".strftime("%Y-%m-%d %H:%M"))
          call append(line(".")+4, "\#Description  : ")
          call append(line(".")+5, "")
        else
          call setline(1,"\#! /usr/bin/env python3")
          call append(line("."), "\#File Name    : ".expand("%"))
          call append(line(".")+1, "\#Author       : ".$author_name)
          call append(line(".")+2, "\#Mail         : ".$author_email)
          call append(line(".")+3, "\#Create Time  : ".strftime("%Y-%m-%d %H:%M"))
          call append(line(".")+4, "\#Description  : ")
          call append(line(".")+5, "")
        endif
      endfunc

      " 新建文件后，自动定位到文件末尾
      autocmd BufNewfile * normal G

- name: vim 配置优化完成
  debug:
    msg: "Vim 配置已追加到 {{ vimrc_path }} 文件"
