- name: 准备 admin 证书签名请求
  template:
    src: admin-csr.json.j2
    dest: "{{ local_pki_dir }}/admin-csr.json"
  register: csr_template_result

- name: 检查 admin.pem 是否存在
  stat:
    path: "{{ local_pki_dir }}/admin.pem"
  register: admin_pem_stat

- name: 创建 admin 证书
  shell: |
    cd {{ local_pki_dir }} &&  \
    {{ cfssl_dir }}/cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -profile=kubernetes \
    admin-csr.json | {{ cfssl_dir }}/cfssljson -bare admin
  register: cert_creation_result
  changed_when: cert_creation_result.rc == 0
  failed_when: cert_creation_result.rc != 0 and "already exists" not in cert_creation_result.stderr
  when: >
    csr_template_result.changed or not admin_pem_stat.stat.exists or _update_components|bool

- name: 检查admin.kubeconfig是否存在
  stat:
    path: "{{ local_kubeconfig_dir }}/admin.kubeconfig"
  register: admin_kubeconfig_stat

- name: 配置 admin kubeconfig
  shell: |
    # 设置集群参数
    {{ kubectl_dir }}/kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority={{ local_pki_dir }}/ca.pem \
    --embed-certs=true \
    --server={{ kube_apiserver }} \
    --kubeconfig={{ local_kubeconfig_dir }}/admin.kubeconfig && \

    # 设置客户端认证参数
    {{ kubectl_dir }}/kubectl config set-credentials admin \
    --client-certificate={{ local_pki_dir }}/admin.pem \
    --client-key={{ local_pki_dir }}/admin-key.pem \
    --embed-certs=true \
    --kubeconfig={{ local_kubeconfig_dir }}/admin.kubeconfig && \

    # 设置上下文参数
    {{ kubectl_dir }}/kubectl config set-context {{ context_name }} \
    --cluster={{ cluster_name }} \
    --user=admin \
    --kubeconfig={{ local_kubeconfig_dir }}/admin.kubeconfig && \

    # 选择默认上下文
    {{ kubectl_dir }}/kubectl config use-context {{ context_name }} \
    --kubeconfig={{ local_kubeconfig_dir }}/admin.kubeconfig
  when: >
    not admin_kubeconfig_stat.stat.exists or _update_components|bool or _update_ca|bool or cert_creation_result.changed
