---
# 系统类型检测变量
is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
is_centos: "{{ ansible_distribution == 'CentOS' or ansible_distribution == 'AlmaLinux' }}"

# 通用内核参数 - 所有系统都适用
common_sysctl_params:
  # 安全参数
  "kernel.panic_on_oops": 1
  "kernel.sysrq": 176
  "kernel.printk": "4 4 1 7"
  "kernel.panic": 10
  "kernel.kptr_restrict": 1
  "kernel.pid_max": 4194303
  "kernel.yama.ptrace_scope": 1

  # 内存管理参数
  "vm.max_map_count": 262144
  "vm.mmap_min_addr": 65536
  "vm.overcommit_memory": 1

  # 文件系统参数
  "fs.file-max": 1048576
  "fs.protected_hardlinks": 1
  "fs.protected_symlinks": 1

  # 网络通用参数
  "net.core.somaxconn": 16384
  "net.core.netdev_max_backlog": 16384

  # 网络连接跟踪参数
  "net.netfilter.nf_conntrack_max": 2097152

  # IPv4网络参数
  "net.ipv4.ip_nonlocal_bind": 1
  "net.ipv4.ip_forward": 1
  "net.ipv4.conf.all.rp_filter": 2
  "net.ipv4.conf.default.rp_filter": 2
  "net.ipv4.tcp_syncookies": 1
  "net.ipv4.tcp_syn_retries": 1
  "net.ipv4.tcp_synack_retries": 1
  "net.ipv4.tcp_tw_reuse": 1
  "net.ipv4.tcp_fin_timeout": 1
  "net.ipv4.tcp_keepalive_time": 1200
  "net.ipv4.tcp_keepalive_intvl": 30
  "net.ipv4.tcp_keepalive_probes": 10
  "net.ipv4.tcp_max_syn_backlog": 16384
  "net.ipv4.tcp_max_tw_buckets": 36000
  "net.ipv4.tcp_max_orphans": 16384
  "net.ipv4.ip_local_port_range": "10000 65535"
  "net.ipv4.route.gc_timeout": 100
  "net.ipv4.tcp_rmem": "4096 4096 16777216"
  "net.ipv4.tcp_wmem": "4096 4096 16777216"
  "net.ipv4.tcp_mem": "786432 2097152 3145728"

  # 网络桥接参数
  "net.bridge.bridge-nf-call-iptables": 1
  "net.bridge.bridge-nf-call-arptables": 1

  # IPv6参数
  "net.ipv6.conf.all.disable_ipv6": 0
  "net.ipv6.conf.default.disable_ipv6": 0
  "net.ipv6.conf.lo.disable_ipv6": 0
  "net.ipv6.conf.all.forwarding": 0
  "net.bridge.bridge-nf-call-ip6tables": 1

# IPVS相关内核模块
ipvs_modules:
- ip_vs
- ip_vs_rr
- ip_vs_wrr
- ip_vs_sh
- nf_conntrack
- br_netfilter
- ip_tables
- ip_set
- xt_set
- ipt_set
- ipt_rpfilter
- ipt_REJECT
- ipip
- overlay
